using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DAL
{
    class CreationTablesSql
    {
//        DROP TABLE KIND
//DROP TABLE PERSON
//DROP TABLE FAMILY
//DROP TABLE PHONE
//DROP TABLE GYMGROUP
//DROP TABLE PERSON_GYMGROUP
//DROP TABLE PAYMENTTYPE
//DROP TABLE PAYMENT
//DROP TABLE DOCUMENTTYPE
//DROP TABLE DOCUMENT
//DROP TABLE DISCOUNT

//CREATE TABLE KIND(
//KINDID INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY,
//KINDNAME            VARCHAR(25)         NOT NULL				
//);

//        CREATE TABLE FAMILY(
//        FAMILYID INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY,
//LASTNAME            VARCHAR(25)         NOT NULL,
//ADDRESS             VARCHAR(100)        NOT NULL,
//ZIPCODE             VARCHAR(10)         NOT NULL,
//CITY                VARCHAR(50)         NOT NULL,
//EMAIL               VARCHAR(150)        NULL													,
//);

//CREATE TABLE DISCOUNT(
//DISCOUNTID INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY,
//FAMILYID            INT NOT NULL												,
//DISCOUNTYEAR INT                 NOT NULL,
//DESCRIPTION         VARCHAR(150)        NULL													,
//AMOUNT REAL                NOT NULL,
//CONSTRAINT fk_DISCOUNT_FAMILY FOREIGN KEY(FAMILYID) REFERENCES FAMILY(FAMILYID)
//);

//CREATE TABLE PERSON(
//PERSONID INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY,
//FAMILYID            INT NOT NULL												,
//KINDID INT                 NOT NULL,
//LASTNAME            VARCHAR(25)         NOT NULL,
//FIRSTNAME           VARCHAR(25)         NOT NULL,
//BIRTHDATE           DATE NULL,
//HOURLYRATE          REAL NULL,
//CONSTRAINT fk_PERSON_KIND FOREIGN KEY(KINDID) REFERENCES KIND(KINDID)                          ,
//CONSTRAINT fk_PERSON_FAMILY FOREIGN KEY(FAMILYID) REFERENCES FAMILY(FAMILYID)
//);										

//CREATE TABLE PHONE(
//PHONEID INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY,
//FAMILYID            INT NOT NULL												,
//PHONENUMBER VARCHAR(25)         NOT NULL,
//CONSTRAINT fk_PHONE_FAMILY FOREIGN KEY(FAMILYID) REFERENCES FAMILY(FAMILYID)
//);

//CREATE TABLE GYMGROUP(
//GYMGROUPID INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY,
//GYMGROUPNAME        VARCHAR(50)         NOT NULL,
//NUMBEROFHOURS       REAL NOT NULL												,
//GYMYEAR INT                 NOT NULL,
//YEARPRICE           REAL NOT NULL				
//);

//CREATE TABLE PERSON_GYMGROUP(
//PERSON_GYMGROUP_ID INT IDENTITY(1,1)   NOT NULL,
//PERSONID            INT NOT NULL												,
//GYMGROUPID INT                 NOT NULL,
//PRIMARY KEY(PERSON_GYMGROUP_ID)                                                                ,
//CONSTRAINT fk_PERSON_GYMGROUP_PERSON FOREIGN KEY(PERSONID) REFERENCES PERSON(PERSONID)         ,
//CONSTRAINT fk_PERSON_GYMGROUP_GYMGROUP FOREIGN KEY(GYMGROUPID) REFERENCES GYMGROUP(GYMGROUPID)
//);

//CREATE TABLE PAYMENTTYPE(
//PAYMENTTYPEID INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY,
//NAME                VARCHAR(25)         NOT NULL
//);

//        CREATE TABLE PAYMENT(
//        PAYMENTID INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY,
//PAYMENTTYPEID       INT NOT NULL												,
//FAMILYID INT                 NOT NULL,
//GYMYEAR             INT NOT NULL												,
//PAYMENTDATE DATE                NOT NULL,
//CHECKNUMBER         INT NULL,
//AMOUNT              REAL NOT NULL												,
//CONSTRAINT fk_PAYMENT_PAYMENTTYPE FOREIGN KEY(PAYMENTTYPEID) REFERENCES PAYMENTTYPE(PAYMENTTYPEID),
//CONSTRAINT fk_PAYMENT_FAMILY FOREIGN KEY(FAMILYID) REFERENCES FAMILY(FAMILYID)
//);

//CREATE TABLE DOCUMENTTYPE(
//DOCUMENTTYPEID INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY,
//DOCUMENTNAME            VARCHAR(50)         NOT NULL,
//MADATORY                SMALLINT NOT NULL
//);

//CREATE TABLE DOCUMENT(
//DOCUMENTID INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY,
//DOCUMENTTYPEID      INT NOT NULL												,
//PERSONID INT                 NOT NULL,
//DOCUMENTYEAR        INT NOT NULL												,
//CONSTRAINT fk_DOCUMENT_DOCUMENTTYPE FOREIGN KEY(DOCUMENTTYPEID) REFERENCES DOCUMENTTYPE(DOCUMENTTYPEID),
//CONSTRAINT fk_DOCUMENT_PERSON FOREIGN KEY(PERSONID) REFERENCES PERSON(PERSONID)
//);
    }
}
