//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCOUNT
    {
        public int DISCOUNTID { get; set; }
        public int FAMILYID { get; set; }
        public int DISCOUNTYEAR { get; set; }
        public string DESCRIPTION { get; set; }
        public float AMOUNT { get; set; }
    
        public virtual FAMILY FAMILY { get; set; }
    }
}
