//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT
    {
        public int DOCUMENTID { get; set; }
        public int DOCUMENTTYPEID { get; set; }
        public int PERSONID { get; set; }
        public int DOCUMENTYEAR { get; set; }
    
        public virtual DOCUMENTTYPE DOCUMENTTYPE { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
