//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EGOEntities : DbContext
    {
        public EGOEntities()
            : base("name=EGOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONTRIBUTION> CONTRIBUTION { get; set; }
        public virtual DbSet<DISCOUNT> DISCOUNT { get; set; }
        public virtual DbSet<DOCUMENT> DOCUMENT { get; set; }
        public virtual DbSet<DOCUMENTTYPE> DOCUMENTTYPE { get; set; }
        public virtual DbSet<FAMILY> FAMILY { get; set; }
        public virtual DbSet<GYMGROUP> GYMGROUP { get; set; }
        public virtual DbSet<KIND> KIND { get; set; }
        public virtual DbSet<PAYMENT> PAYMENT { get; set; }
        public virtual DbSet<PAYMENTTYPE> PAYMENTTYPE { get; set; }
        public virtual DbSet<PERSON> PERSON { get; set; }
        public virtual DbSet<PERSON_GYMGROUP> PERSON_GYMGROUP { get; set; }
        public virtual DbSet<PERSON_KIND> PERSON_KIND { get; set; }
        public virtual DbSet<PHONE> PHONE { get; set; }
        public virtual DbSet<TRANSLATION> TRANSLATION { get; set; }
    }
}
