//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EGOEntities : DbContext
    {
        public EGOEntities()
            : base("name=EGOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DISCOUNT> DISCOUNT { get; set; }
        public virtual DbSet<DOCUMENT> DOCUMENT { get; set; }
        public virtual DbSet<DOCUMENTTYPE> DOCUMENTTYPE { get; set; }
        public virtual DbSet<FAMILY> FAMILY { get; set; }
        public virtual DbSet<GYMGROUP> GYMGROUP { get; set; }
        public virtual DbSet<KIND> KIND { get; set; }
        public virtual DbSet<PAYMENT> PAYMENT { get; set; }
        public virtual DbSet<PAYMENTTYPE> PAYMENTTYPE { get; set; }
        public virtual DbSet<PERSON> PERSON { get; set; }
        public virtual DbSet<PERSON_GYMGROUP> PERSON_GYMGROUP { get; set; }
        public virtual DbSet<PERSON_KIND> PERSON_KIND { get; set; }
        public virtual DbSet<PHONE> PHONE { get; set; }
        public virtual DbSet<TRANSLATION> TRANSLATION { get; set; }
    }
}
