//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GYMGROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GYMGROUP()
        {
            this.PERSON_GYMGROUP = new HashSet<PERSON_GYMGROUP>();
        }
    
        public int GYMGROUPID { get; set; }
        public string GYMGROUPNAME { get; set; }
        public float NUMBEROFHOURS { get; set; }
        public int GYMYEAR { get; set; }
        public float YEARPRICE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSON_GYMGROUP> PERSON_GYMGROUP { get; set; }
    }
}
