//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public int PAYMENTID { get; set; }
        public int PAYMENTTYPEID { get; set; }
        public int FAMILYID { get; set; }
        public int GYMYEAR { get; set; }
        public System.DateTime PAYMENTDATE { get; set; }
        public Nullable<int> CHECKNUMBER { get; set; }
        public float AMOUNT { get; set; }
    
        public virtual FAMILY FAMILY { get; set; }
        public virtual PAYMENTTYPE PAYMENTTYPE { get; set; }
    }
}
