//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONE
    {
        public int PHONEID { get; set; }
        public int FAMILYID { get; set; }
        public string PHONENUMBER { get; set; }
    
        public virtual FAMILY FAMILY { get; set; }
    }
}
