using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace EGOFormsApp.Common
{
    public static class Database
    {
        public static void Create()
        {
            string connectionString = "Server= localhost; Database= EGO; Integrated Security=True;";

            using (SqlConnection con = new SqlConnection(connectionString))
            {

                try
                {
                    con.Open();

                    using (SqlCommand command = new SqlCommand(CreationQuery, con))
                        command.ExecuteNonQuery();
                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                }
            }
        }
        public static void Drop()
        {
            string connectionString = "Server= localhost; Database= EGO; Integrated Security=True;";

            using (SqlConnection con = new SqlConnection(connectionString))
            {

                try
                {
                    con.Open();

                    using (SqlCommand command = new SqlCommand(DropQuery, con))
                        command.ExecuteNonQuery();
                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                }
            }
        }

        const string DropQuery = @"
DROP TABLE TRANSLATION
DROP TABLE PERSON_GYMGROUP
DROP TABLE GYMGROUP
DROP TABLE PHONE
DROP TABLE DISCOUNT
DROP TABLE DOCUMENT
DROP TABLE PAYMENT
DROP TABLE PAYMENTTYPE
DROP TABLE DOCUMENTTYPE
DROP TABLE PERSON_KIND
DROP TABLE PERSON
DROP TABLE KIND
DROP TABLE FAMILY
DROP TABLE CONTRIBUTION";

        const string CreationQuery = @"
CREATE TABLE CONTRIBUTION(
CONTRIBUTIONID		INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY	,
GYMYEAR				INT                 NOT NULL				,
AMOUNT				REAL                NOT NULL				,
);

CREATE TABLE TRANSLATION(
TRANSLATIONKEY		VARCHAR(25)         NOT NULL    PRIMARY KEY	,
WORDS               VARCHAR(150)        NOT NULL				,
LANG				VARCHAR(5)			NOT NULL
)

CREATE TABLE KIND(
KINDID				INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY	,
KINDNAME            VARCHAR(25)         NOT NULL				
);

CREATE TABLE FAMILY(
FAMILYID			INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY	,
LASTNAME            VARCHAR(25)         NOT NULL				,
ADDRESS             VARCHAR(100)        NOT NULL				,
ZIPCODE             VARCHAR(10)         NOT NULL				,
CITY                VARCHAR(50)         NOT NULL				,
EMAIL               VARCHAR(150)        NULL					,
);

CREATE TABLE DISCOUNT(
DISCOUNTID			INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY	,
FAMILYID            INT					NOT NULL				,
DISCOUNTYEAR		INT                 NOT NULL				,
DESCRIPTION         VARCHAR(150)        NULL					,
AMOUNT				REAL                NOT NULL				,
CONSTRAINT fk_DISCOUNT_FAMILY FOREIGN KEY(FAMILYID) REFERENCES FAMILY(FAMILYID)
);

CREATE TABLE PERSON(
PERSONID			INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY	,
FAMILYID            INT					NOT NULL				,
LASTNAME			VARCHAR(25)         NOT NULL				,
FIRSTNAME           VARCHAR(25)         NOT NULL				,
BIRTHDATE           DATE				NULL					,
HOURLYRATE          REAL				NULL					,
CONSTRAINT fk_PERSON_FAMILY FOREIGN KEY(FAMILYID) REFERENCES FAMILY(FAMILYID)
);

CREATE TABLE PERSON_KIND(
PERSON_KIND_ID		INT IDENTITY(1,1)   NOT NULL	PRIMARY KEY	,
PERSONID            INT					NOT NULL				,
KINDID				INT                 NOT NULL				,
CONSTRAINT fk_PERSON_KIND_PERSON FOREIGN KEY(PERSONID) REFERENCES PERSON(PERSONID),
CONSTRAINT fk_PERSON_KIND_KIND FOREIGN KEY(KINDID) REFERENCES KIND(KINDID),
CONSTRAINT u_PERSON_KIND UNIQUE(PERSONID, KINDID)
);

CREATE TABLE PHONE(
PHONEID				INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY	,
FAMILYID            INT					NOT NULL				,
PHONENUMBER			VARCHAR(25)         NOT NULL				,
CONSTRAINT fk_PHONE_FAMILY FOREIGN KEY(FAMILYID) REFERENCES FAMILY(FAMILYID)
);

CREATE TABLE GYMGROUP(
GYMGROUPID			INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY	,
GYMGROUPNAME        VARCHAR(150)         NOT NULL				,
NUMBEROFHOURS       REAL				NOT NULL				,
GYMGROUPYEAR		INT                 NOT NULL				,
YEARPRICE           REAL				NOT NULL				
);

CREATE TABLE PERSON_GYMGROUP(
PERSON_GYMGROUP_ID	INT IDENTITY(1,1)   NOT NULL	PRIMARY KEY	,
PERSONID            INT					NOT NULL				,
GYMGROUPID			INT                 NOT NULL				,
CONSTRAINT fk_PERSON_GYMGROUP_PERSON FOREIGN KEY(PERSONID) REFERENCES PERSON(PERSONID),
CONSTRAINT fk_PERSON_GYMGROUP_GYMGROUP FOREIGN KEY(GYMGROUPID) REFERENCES GYMGROUP(GYMGROUPID),
CONSTRAINT u_PERSON_GYMGROUP UNIQUE(PERSONID, GYMGROUPID)
);

CREATE TABLE PAYMENTTYPE(
PAYMENTTYPEID		INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY	,
NAME                VARCHAR(25)         NOT NULL
);

CREATE TABLE PAYMENT(
PAYMENTID			INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY	,
PAYMENTTYPEID       INT					NOT NULL				,
FAMILYID			INT                 NOT NULL				,
GYMYEAR             INT					NOT NULL				,
PAYMENTDATE			DATE                NOT NULL				,
CHECKNUMBER         INT					NULL					,
AMOUNT              REAL				NOT NULL				,
CONSTRAINT fk_PAYMENT_PAYMENTTYPE FOREIGN KEY(PAYMENTTYPEID) REFERENCES PAYMENTTYPE(PAYMENTTYPEID),
CONSTRAINT fk_PAYMENT_FAMILY FOREIGN KEY(FAMILYID) REFERENCES FAMILY(FAMILYID)
);

CREATE TABLE DOCUMENTTYPE(
DOCUMENTTYPEID		INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY	,
DOCUMENTNAME            VARCHAR(50)     NOT NULL				,
MADATORY                SMALLINT		NOT NULL
);

CREATE TABLE DOCUMENT(
DOCUMENTID			INT IDENTITY(1,1)   NOT NULL    PRIMARY KEY	,
DOCUMENTTYPEID      INT					NOT NULL				,
PERSONID			INT                 NOT NULL				,
DOCUMENTYEAR		INT					NOT NULL				,
CONSTRAINT fk_DOCUMENT_DOCUMENTTYPE FOREIGN KEY(DOCUMENTTYPEID) REFERENCES DOCUMENTTYPE(DOCUMENTTYPEID),
CONSTRAINT fk_DOCUMENT_PERSON FOREIGN KEY(PERSONID) REFERENCES PERSON(PERSONID)
);

INSERT INTO CONTRIBUTION VALUES (2020, 35)

INSERT INTO KIND VALUES ('SUBSCRIBER')
INSERT INTO KIND VALUES ('COACH')

INSERT INTO DOCUMENTTYPE VALUES('Fiche d''information', 1)
INSERT INTO DOCUMENTTYPE VALUES('Autorisation parentale', 1)
INSERT INTO DOCUMENTTYPE VALUES('Photo', 1)
INSERT INTO DOCUMENTTYPE VALUES('Certificat médical', 1)

INSERT INTO PAYMENTTYPE VALUES ('ESPECE')
INSERT INTO PAYMENTTYPE VALUES ('CHEQUE')


INSERT TRANSLATION VALUES(N'ADDRESS', N'Adresse', N'FR')
INSERT TRANSLATION VALUES(N'AMOUNT', N'Montant', N'FR')
INSERT TRANSLATION VALUES(N'BIRTHDATE', N'Date de naissance', N'FR')
INSERT TRANSLATION VALUES(N'CHECKNUMBER', N'Numéro de chèque', N'FR')
INSERT TRANSLATION VALUES(N'CITY', N'Ville', N'FR')
INSERT TRANSLATION VALUES(N'COACH', N'Coach', N'FR')
INSERT TRANSLATION VALUES(N'DESCRIPTION', N'Description', N'FR')
INSERT TRANSLATION VALUES(N'DISCOUNTYEAR', N'Année', N'FR')
INSERT TRANSLATION VALUES(N'EMAIL', N'Email', N'FR')
INSERT TRANSLATION VALUES(N'Enregistrer', N'Enregistrer', N'FR')
INSERT TRANSLATION VALUES(N'FAMILYNAME', N'Famille', N'FR')
INSERT TRANSLATION VALUES(N'FIRSTNAME', N'Prénom', N'FR')
INSERT TRANSLATION VALUES(N'GYMYEAR', N'Année', N'FR')
INSERT TRANSLATION VALUES(N'HOURLYRATE', N'Taux horaire', N'FR')
INSERT TRANSLATION VALUES(N'LASTNAME', N'Nom', N'FR')
INSERT TRANSLATION VALUES(N'PAYMENTDATE', N'Date d''encaissement', N'FR')
INSERT TRANSLATION VALUES(N'PAYMENTTYPENAME', N'Moyen de paiment', N'FR')
INSERT TRANSLATION VALUES(N'PHONENUMBER', N'Téléphone', N'FR')
INSERT TRANSLATION VALUES(N'Rechercher', N'Rechercher', N'FR')
INSERT TRANSLATION VALUES(N'SUBSCRIBER', N'Adhérent', N'FR')
INSERT TRANSLATION VALUES(N'ZIPCODE', N'Code postal', N'FR')";
    }
}
